### ISSUE TITLE
Minecraft schließt sich nach Start

### ISSUE THREAD

**Issue by innbi** [AtomSponge/hosencorp-2#11]
Hallo Schwamm!

Muss jetzt leider auch einen Bug melden da ich nicht mehr weiter weiß!
Und zwar geht es um folgendes: Beim Start von Minecraft funktioniert noch alles. Ich komme bis zur Weltauswahl des singleplayers. Wenn ich die Welt starte, kommt dieser Dirt hintergrund und nach den Zeilen: Loading terrain, beendet sich Minecraft einfach. 
Habe das modpack neu installiert und auch versuch eine neue Welt zu starten, alles jedoch erfolglos.

Zugewiesener  RaM sind 7GB
Habe es allerdings auch schon mit 4 Probiert. Allerdings keine Veränderung

Hoffe du kannst mir irgendwie weiterhelfen ;) 
Mfg Innbi

Hoffe dir Hilft der Crashlog weiter, da er mir rein gar nichts sagt ;)

Crashlog:
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 08.11.15 18:47
Description: Starting integrated server

java.lang.ExceptionInInitializerError
    at net.minecraft.server.MinecraftServer.<init>(MinecraftServer.java:146)
    at net.minecraft.server.integrated.IntegratedServer.<init>(IntegratedServer.java:45)
    at net.minecraft.client.Minecraft.func_71371_a(Minecraft.java:2091)
    at cpw.mods.fml.client.FMLClientHandler.tryLoadExistingWorld(FMLClientHandler.java:696)
    at net.minecraft.client.gui.GuiSelectWorld.func_146615_e(GuiSelectWorld.java:183)
    at net.minecraft.client.gui.GuiSelectWorld$List.func_148144_a(GuiSelectWorld.java:257)
    at net.minecraft.client.gui.GuiSlot.func_148128_a(GuiSlot.java:209)
    at net.minecraft.client.gui.GuiSelectWorld.func_73863_a(GuiSelectWorld.java:216)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)
    at weather2.weathersystem.EntityRendererProxyWeather2Mini.func_78480_b(EntityRendererProxyWeather2Mini.java:50)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.IllegalStateException: failed to create a child event loop
    at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:61)
    at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:49)
    at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:61)
    at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:52)
    at net.minecraft.network.NetworkSystem.<clinit>(NetworkSystem.java:47)
    ... 19 more
Caused by: io.netty.channel.ChannelException: failed to open a new selector
    at io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:128)
    at io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:120)
    at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:87)
    at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:57)
    ... 23 more
Caused by: java.io.IOException: Unable to establish loopback connection
    at sun.nio.ch.PipeImpl$Initializer.run(Unknown Source)
    at sun.nio.ch.PipeImpl$Initializer.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at sun.nio.ch.PipeImpl.<init>(Unknown Source)
    at sun.nio.ch.SelectorProviderImpl.openPipe(Unknown Source)
    at java.nio.channels.Pipe.open(Unknown Source)
    at sun.nio.ch.WindowsSelectorImpl.<init>(Unknown Source)
    at sun.nio.ch.WindowsSelectorProvider.openSelector(Unknown Source)
    at io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:126)
    ... 26 more
Caused by: java.net.ConnectException: Connection timed out: connect
    at sun.nio.ch.Net.connect0(Native Method)
    at sun.nio.ch.Net.connect(Unknown Source)
    at sun.nio.ch.Net.connect(Unknown Source)
    at sun.nio.ch.SocketChannelImpl.connect(Unknown Source)
    at java.nio.channels.SocketChannel.open(Unknown Source)
    at sun.nio.ch.PipeImpl$Initializer$LoopbackConnector.run(Unknown Source)
    ... 35 more

**Comment by AtomSponge** [comment]
Welches System nutzt du?
Versuch mal, 127.0.0.1 anzupingen, Ausgabe bitte hier posten.

**Comment by innbi** [comment]
Ich benutze Windows 10.

Ping-Statistik für 127.0.0.1:
    Pakete: Gesendet = 4, Empfangen = 4, Verloren = 0
    (0% Verlust),
Ca. Zeitangaben in Millisek.:
    Minimum = 0ms, Maximum = 1ms, Mittelwert = 0ms

**Comment by AtomSponge** [comment]
Nutzt du ein Antivirus? Wenn ja, welches?
Tritt der Fehler immer reproduzierbar auf? Auch bei anderen Modpacks/"Vanilla" Minecraft?

**Comment by AtomSponge** [comment]
Aufgrund der Inaktivität seitens des Ticket-Autors nehmen wir an, dass der Fehler selbstständig behoben wurde.
