### ISSUE TITLE
Problem beim starten 

### ISSUE THREAD

**Issue by TheWilhelm** [AtomSponge/hosencorp-2#15]
hi ich habe ein Linux spezifisches Problem gefunden.
ich habe die Dateien für die Version 1.2 runter geladen und auf Windows,
getestet. dort funktionierte alles, als ich dann versuchte es auf einem Linux
Server zu starten gab es eine größere mänge Fehler die verhindert haben
das der Server startet.

Server Details OS: 
Debian 7.0 64-bit
java -version:
java version "1.6.0_36"
OpenJDK Runtime Environment (IcedTea6 1.13.8) (6b36-1.13.8-1~deb7u1)
OpenJDK 64-Bit Server VM (build 23.25-b01, mixed mode)

alles in der neusten verfügbaren Version

der Konsolen Output

```
[10:17:55] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLServerTweaker
[10:17:55] [main/INFO] [LaunchWrapper]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLServerTweaker
[10:17:55] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLServerTweaker
[10:17:55] [main/INFO] [FML]: Forge Mod Loader version 7.99.36.1558 for Minecraft 1.7.10 loading
[10:17:55] [main/INFO] [FML]: Java is OpenJDK 64-Bit Server VM, version 1.6.0_36, running on Linux:amd64:2.6.32-43-pve, installed at /usr/lib/jvm/java-6-openjdk-amd64/jre
[10:17:56] [main/INFO] [FML]: [AppEng] Core Init
[10:17:56] [main/WARN] [FML]: The coremod aroma1997.core.coremod.CoreMod does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[10:17:56] [main/WARN] [FML]: The coremod codechicken.core.launch.CodeChickenCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[10:17:57] [main/WARN] [FML]: The coremod cofh.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[10:17:57] [main/WARN] [FML]: The coremod fastcraft.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[10:17:57] [main/WARN] [FML]: The coremod codechicken.core.launch.DepLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[10:17:57] [main/WARN] [FML]: The coremod invtweaks.forge.asm.FMLPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[10:17:57] [main/WARN] [FML]: The coremod logisticspipes.asm.LogisticsPipesCoreLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[10:17:57] [main/WARN] [FML]: The coremod net.malisis.core.asm.MalisisCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[10:17:57] [main/WARN] [FML]: The coremod mariculture.fishery.VanillaOverride does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[10:17:57] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:478]: java.lang.UnsupportedClassVersionError: mekanism/common/asm/LoadingHook : Unsupported major.minor version 51.0
[10:17:57] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:481]:     at java.lang.ClassLoader.defineClass1(Native Method)
[10:17:57] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:481]:     at java.lang.ClassLoader.defineClass(ClassLoader.java:643)
[10:17:57] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:481]:     at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[10:17:57] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:481]:     at java.net.URLClassLoader.defineClass(URLClassLoader.java:277)
[10:17:57] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:481]:     at java.net.URLClassLoader.access$000(URLClassLoader.java:73)
[10:17:57] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:481]:     at java.net.URLClassLoader$1.run(URLClassLoader.java:212)
[10:17:57] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:481]:     at java.security.AccessController.doPrivileged(Native Method)
[10:17:57] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:481]:     at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
[10:17:57] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:481]:     at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117)
[10:17:57] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:481]:     at java.lang.ClassLoader.loadClass(ClassLoader.java:323)
[10:17:57] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:481]:     at java.lang.ClassLoader.loadClass(ClassLoader.java:268)
[10:17:57] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:481]:     at java.lang.Class.forName0(Native Method)
[10:17:57] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:481]:     at java.lang.Class.forName(Class.java:274)
[10:17:57] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:481]:     at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:460)
[10:17:57] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:481]:     at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:389)
[10:17:57] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:481]:     at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:221)
[10:17:57] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:481]:     at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90)
[10:17:57] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:481]:     at cpw.mods.fml.relauncher.FMLLaunchHandler.setupServer(FMLLaunchHandler.java:74)
[10:17:57] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:481]:     at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForServerLaunch(FMLLaunchHandler.java:39)
[10:17:57] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:481]:     at cpw.mods.fml.common.launcher.FMLServerTweaker.injectIntoClassLoader(FMLServerTweaker.java:23)
[10:17:57] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:481]:     at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[10:17:57] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:481]:     at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[10:17:57] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:481]:     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[10:17:57] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:481]:     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[10:17:57] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:481]:     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[10:17:57] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:481]:     at java.lang.reflect.Method.invoke(Method.java:622)
[10:17:57] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:481]:     at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43)
[10:17:57] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:481]:     at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12)
[10:17:57] [main/ERROR] [FML]: An error occurred trying to configure the minecraft home at /home/minecraft/. for Forge Mod Loader
java.lang.UnsupportedClassVersionError: mekanism/common/asm/LoadingHook : Unsupported major.minor version 51.0
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.6.0_36]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:643) ~[?:1.6.0_36]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.6.0_36]
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:277) ~[?:1.6.0_36]
        at java.net.URLClassLoader.access$000(URLClassLoader.java:73) ~[?:1.6.0_36]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:212) ~[?:1.6.0_36]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.6.0_36]
        at java.net.URLClassLoader.findClass(URLClassLoader.java:205) ~[?:1.6.0_36]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:323) ~[?:1.6.0_36]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:268) ~[?:1.6.0_36]
        at java.lang.Class.forName0(Native Method) ~[?:1.6.0_36]
        at java.lang.Class.forName(Class.java:274) ~[?:1.6.0_36]
        at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:460) ~[forge-1.7.10-10.13.4.1558-1.7.10-universal.jar:?]
        at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:389) ~[forge-1.7.10-10.13.4.1558-1.7.10-universal.jar:?]
        at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:221) ~[forge-1.7.10-10.13.4.1558-1.7.10-universal.jar:?]
        at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90) [forge-1.7.10-10.13.4.1558-1.7.10-universal.jar:?]
        at cpw.mods.fml.relauncher.FMLLaunchHandler.setupServer(FMLLaunchHandler.java:74) [forge-1.7.10-10.13.4.1558-1.7.10-universal.jar:?]
        at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForServerLaunch(FMLLaunchHandler.java:39) [forge-1.7.10-10.13.4.1558-1.7.10-universal.jar:?]
        at cpw.mods.fml.common.launcher.FMLServerTweaker.injectIntoClassLoader(FMLServerTweaker.java:23) [forge-1.7.10-10.13.4.1558-1.7.10-universal.jar:?]
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.6.0_36]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.6.0_36]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.6.0_36]
        at java.lang.reflect.Method.invoke(Method.java:622) ~[?:1.6.0_36]
        at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43) [forge-1.7.10-10.13.4.1558-1.7.10-universal.jar:?]
        at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12) [forge-1.7.10-10.13.4.1558-1.7.10-universal.jar:?]
A problem occurred running the Server launcher.[10:17:57] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:478]: java.lang.reflect.InvocationTargetException
[10:17:57] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:481]:     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[10:17:57] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:481]:     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[10:17:57] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:481]:     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[10:17:57] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:481]:     at java.lang.reflect.Method.invoke(Method.java:622)
[10:17:57] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:481]:     at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43)
[10:17:57] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:481]:     at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12)
[10:17:57] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:505]: Caused by: java.lang.UnsupportedClassVersionError: mekanism/common/asm/LoadingHook : Unsupported major.minor version 51.0
[10:17:57] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:507]:      at java.lang.ClassLoader.defineClass1(Native Method)
[10:17:57] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:507]:      at java.lang.ClassLoader.defineClass(ClassLoader.java:643)
[10:17:57] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:507]:      at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[10:17:57] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:507]:      at java.net.URLClassLoader.defineClass(URLClassLoader.java:277)
[10:17:57] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:507]:      at java.net.URLClassLoader.access$000(URLClassLoader.java:73)
[10:17:57] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:507]:      at java.net.URLClassLoader$1.run(URLClassLoader.java:212)
[10:17:57] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:507]:      at java.security.AccessController.doPrivileged(Native Method)
[10:17:57] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:507]:      at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
[10:17:57] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:507]:      at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117)
[10:17:57] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:507]:      at java.lang.ClassLoader.loadClass(ClassLoader.java:323)
[10:17:57] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:507]:      at java.lang.ClassLoader.loadClass(ClassLoader.java:268)
[10:17:57] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:507]:      at java.lang.Class.forName0(Native Method)
[10:17:57] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:507]:      at java.lang.Class.forName(Class.java:274)
[10:17:57] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:507]:      at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:460)
[10:17:57] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:507]:      at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:389)
[10:17:57] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:507]:      at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:221)
[10:17:57] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:507]:      at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90)
[10:17:57] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:507]:      at cpw.mods.fml.relauncher.FMLLaunchHandler.setupServer(FMLLaunchHandler.java:74)
[10:17:57] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:507]:      at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForServerLaunch(FMLLaunchHandler.java:39)
[10:17:57] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:507]:      at cpw.mods.fml.common.launcher.FMLServerTweaker.injectIntoClassLoader(FMLServerTweaker.java:23)
[10:17:57] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:507]:      at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[10:17:57] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:507]:      at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[10:17:57] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:509]:      ... 6 more
```

die latest.log Datei ist leer

[fml-junk-earlystartup.txt](https://github.com/AtomSponge/hosencorp-2/files/93489/fml-junk-earlystartup.txt)
[fml-server-latest.txt](https://github.com/AtomSponge/hosencorp-2/files/93490/fml-server-latest.txt)

**Comment by Bandelenth** [comment]
Das Problem ist, dass die Java-Version viel zu alt ist. Ich weiß ehrlich gesagt nicht auswendig, ob bei Debian 8 Java 1.8 (bzw. 8) in den Paketquellen mitgeliefert wird, es ist aber aufgrund der erhöhten Leistung sowieso empfehlenswert das Oracle Java anstelle des OpenJDK-Javas zu verwenden.
