### ISSUE TITLE
Server Probleme

### ISSUE THREAD

**Issue by MrBasticraft** [AtomSponge/hosencorp-2#19]
[12:58:38] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[12:58:38] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[12:58:38] [main/INFO] [Aroma1997Core]: Finished data injection.
[12:58:38] [main/INFO] [Aroma1997Core]: Finished data injection.
[12:58:38] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[12:58:38] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[12:58:38] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[12:58:38] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[12:58:39] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[12:58:39] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[12:58:39] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[12:58:39] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[12:58:39] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[12:58:39] [main/INFO] [STDOUT]: [micdoodle8.mods.miccore.MicdoodlePlugin:getASMTransformerClass:102]: Successfully Registered Transformer
[12:58:40] [main/INFO] [STDOUT]: [micdoodle8.mods.miccore.MicdoodlePlugin:injectData:295]: [Micdoodle8Core]: Patching game...
[12:58:40] [main/INFO] [STDOUT]: [micdoodle8.mods.miccore.MicdoodlePlugin:injectData:295]: [Micdoodle8Core]: Patching game...
[12:58:40] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[12:58:40] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[12:58:41] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[12:58:41] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[12:58:41] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[12:58:41] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[12:58:41] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[12:58:41] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[12:58:41] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[12:58:41] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[12:58:41] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLDeobfTweaker
[12:58:42] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[12:58:42] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[12:58:42] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[12:58:43] [main/INFO] [malisiscore]: [ChunkCollisionTransformer] Hook registered for net.minecraft.world.World
[12:58:43] [main/INFO] [malisiscore]: [ChunkCollisionTransformer] Hook registered for net.minecraft.world.World
[12:58:43] [main/INFO] [malisiscore]: [ChunkCollisionTransformer] Hook registered for net.minecraft.item.ItemBlock
[12:58:43] [main/INFO] [malisiscore]: [ChunkCollisionTransformer] Hook registered for net.minecraft.network.NetHandlerPlayServer
[12:58:43] [main/INFO] [malisiscore]: [ChunkBlockTransformer] Hook registered for net.minecraft.world.chunk.Chunk
[12:58:43] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[12:58:43] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.TerminalTweaker
[12:58:43] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.TerminalTweaker
[12:58:43] [main/INFO] [MobiusCore]: Current code is OBFUSCATED
[12:58:43] [main/INFO] [MobiusCore]: [MobiusCore] Found net.minecraft.world.WorldServer [ mt ] with checksum C886BCD50DD675F403ECA0A1C11D15FA
[12:58:43] [main/INFO] [MobiusCore]: Successful injection in b ()V
[12:58:43] [main/INFO] [MobiusCore]: Successful injection in b ()V
[12:58:44] [main/INFO] [MobiusCore]: Found cpw.mods.fml.common.FMLCommonHandler with checksum F626A08BBC07AE3F7D88072FDFDAE36E
[12:58:44] [main/INFO] [MobiusCore]: Successful injection in onPreServerTick ()V
[12:58:44] [main/INFO] [MobiusCore]: Successful injection in onPostServerTick ()V
[12:58:44] [main/INFO] [MobiusCore]: Successful injection in onPreWorldTick (Lahb;)V
[12:58:44] [main/INFO] [MobiusCore]: Successful injection in onPostWorldTick (Lahb;)V
[12:58:44] [main/INFO] [MobiusCore]: Switching injection mode to FORGE
[12:58:44] [main/INFO] [MobiusCore]: [MobiusCore] Found net.minecraft.world.World [ ahb ] with checksum 6F63217CD3C0E529723529895D51BC16
[12:58:44] [main/INFO] [MobiusCore]: Found World.updateEntities()...
[12:58:44] [main/INFO] [MobiusCore]: Successful injection in h ()V
[12:58:44] [main/INFO] [MobiusCore]: Successful injection in h ()V
[12:58:44] [main/INFO] [MobiusCore]: Successful injection in h ()V
[12:58:44] [main/INFO] [MobiusCore]: Successful injection in h ()V
[12:58:44] [main/INFO] [MobiusCore]: Found World.<init> (Lazc;Ljava/lang/String;Lahj;Laqo;Lqi;)V
[12:58:44] [main/INFO] [MobiusCore]: Successful injection in <init> (Lazc;Ljava/lang/String;Lahj;Laqo;Lqi;)V
[12:58:44] [main/INFO] [MobiusCore]: Successful injection in <init> (Lazc;Ljava/lang/String;Lahj;Laqo;Lqi;)V
[12:58:44] [main/INFO] [malisiscore]: Found hooks for net.minecraft.world.World (ahb)
[12:58:45] [main/INFO] [STDOUT]: [micdoodle8.mods.miccore.MicdoodleTransformer:printLog:1848]: Galacticraft successfully injected bytecode into: oi (4 / 4)
[12:58:45] [main/INFO] [STDOUT]: [micdoodle8.mods.miccore.MicdoodleTransformer:printLog:1848]: Galacticraft successfully injected bytecode into: sv (1 / 1)
[12:58:45] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.server.MinecraftServer}
[12:58:46] [main/INFO] [STDOUT]: [micdoodle8.mods.miccore.MicdoodleTransformer:printLog:1848]: Galacticraft successfully injected bytecode into: xk (1 / 1)
[12:58:46] [main/INFO] [Mariculture]: Patching the vanilla class: adb
[12:58:46] [main/INFO] [Mariculture]: Succesfully replaced Vanilla Fishing Rod and Fish
[12:58:46] [main/INFO] [FastLeafDecay]: Patching leaves.
[12:58:46] [main/INFO] [FastLeafDecay]: Found Leave Class: net/minecraft/block/BlockLeavesBase
[12:58:48] [main/INFO] [OpenComputers]: Successfully patched sw.recreateLeash.
[12:58:48] [main/INFO] [malisiscore]: Found hooks for net.minecraft.item.ItemBlock (abh)
[12:58:48] [main/INFO] [InfiniBows]: Fix injected.
[12:58:48] [main/INFO] [STDOUT]: [micdoodle8.mods.miccore.MicdoodleTransformer:printLog:1848]: Galacticraft successfully injected bytecode into: zc (1 / 1)
[12:58:48] [main/INFO] [EnderCore]: Transforming Class [net.minecraft.entity.projectile.EntityArrow], Method [func_70071_h_]
[12:58:48] [main/INFO] [EnderCore]: Transforming net.minecraft.entity.projectile.EntityArrow Finished.
[12:58:49] [main/INFO] [EnderCore]: Transforming Class [net.minecraft.item.ItemStack], Method [func_77953_t]
[12:58:49] [main/INFO] [EnderCore]: Transforming net.minecraft.item.ItemStack Finished.
[12:58:49] [main/INFO] [FML]: InvTweaks: net.minecraft.inventory.Container
[12:58:49] [main/INFO] [FML]: InvTweaks: net.minecraft.inventory.ContainerFurnace
[12:58:49] [main/INFO] [EnderCore]: Transforming Class [net.minecraft.inventory.ContainerFurnace], Method [func_82846_b]
[12:58:49] [main/INFO] [EnderCore]: Transforming net.minecraft.inventory.ContainerFurnace Finished.
[12:58:50] [Server thread/INFO]: Starting minecraft server version 1.7.10
[12:58:50] [Server thread/INFO] [MinecraftForge]: Attempting early MinecraftForge initialization
[12:58:50] [Server thread/INFO] [FML]: MinecraftForge v10.13.4.1558 Initialized
[12:58:50] [Server thread/INFO] [FML]: Replaced 183 ore recipies
[12:58:50] [Server thread/INFO] [MinecraftForge]: Completed early MinecraftForge initialization
[12:58:50] [Server thread/INFO] [FML]: [AppEng] Core Init
[12:58:51] [Server thread/INFO] [FML]: Found 0 mods from the command line. Injecting into mod discoverer
[12:58:51] [Server thread/INFO] [FML]: Searching /games/ni248314_1/ftproot/minecraftotherpacks/mods for mods
[12:58:51] [Server thread/INFO] [FML]: Also searching /games/ni248314_1/ftproot/minecraftotherpacks/mods/1.7.10 for mods
[12:58:51] [Server thread/INFO] [AppleCore]: Mod AppleCore is missing the required element 'name'. Substituting AppleCore
[12:58:52] [Server thread/WARN] [Aroma1997CoreHelper]: Mod Aroma1997CoreHelper is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 1.0.2.16
[12:58:52] [Server thread/WARN] [Aroma1997sDimension]: Mod Aroma1997sDimension is missing the required element 'version' and no fallback can be found. Substituting '1.0'.
[12:58:53] [Server thread/WARN] [Botany]: Mod Botany is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 2.0-pre14
[12:58:53] [Server thread/WARN] [BinnieCore]: Mod BinnieCore is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 2.0-pre14
[12:58:53] [Server thread/WARN] [ExtraBees]: Mod ExtraBees is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 2.0-pre14
[12:58:53] [Server thread/WARN] [ExtraTrees]: Mod ExtraTrees is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 2.0-pre14
[12:58:53] [Server thread/WARN] [Genetics]: Mod Genetics is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 2.0-pre14
[12:58:54] [Server thread/WARN] [ChickenChunks]: Mod ChickenChunks is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 1.3.4.19
[12:58:54] [Server thread/WARN] [ChiselFacades]: Mod ChiselFacades is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 1.7.10-2.10-cricket
[12:58:55] [Server thread/INFO] [debug]: Mod debug is missing the required element 'name'. Substituting debug
[12:58:55] [Server thread/WARN] [debug]: Mod debug is missing the required element 'version' and no fallback can be found. Substituting '1.0'.
[12:58:55] [Server thread/WARN] [EnderStorage]: Mod EnderStorage is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 1.4.7.37
[12:58:56] [Server thread/WARN] [ExtraUtilities]: Mod ExtraUtilities is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 1.2.12
[12:58:58] [Server thread/WARN] [IGWMod]: Mod IGWMod is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 1.1.11-32
[12:58:59] [Server thread/WARN] [Mariculture]: Mod Mariculture is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 1.7.10-1.2.4.2a
[12:58:59] [Server thread/WARN] [MariTech]: Mod MariTech is missing the required element 'version' and no fallback can be found. Substituting '1.0'.
[12:59:02] [Server thread/WARN] [PneumaticCraft]: Mod PneumaticCraft is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 1.12.3-146
[12:59:02] [Server thread/WARN] [ProjRed|Core]: Mod ProjRed|Core is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 4.7.0pre9.92
[12:59:02] [Server thread/WARN] [ProjRed|Compatibility]: Mod ProjRed|Compatibility is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 4.7.0pre9.92
[12:59:02] [Server thread/WARN] [ProjRed|Fabrication]: Mod ProjRed|Fabrication is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 4.7.0pre9.92
[12:59:03] [Server thread/WARN] [ProjRed|Integration]: Mod ProjRed|Integration is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 4.7.0pre9.92
[12:59:03] [Server thread/WARN] [ProjRed|Transmission]: Mod ProjRed|Transmission is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 4.7.0pre9.92
[12:59:03] [Server thread/WARN] [ProjRed|Illumination]: Mod ProjRed|Illumination is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 4.7.0pre9.92
[12:59:03] [Server thread/WARN] [ProjRed|Exploration]: Mod ProjRed|Exploration is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 4.7.0pre9.92
[12:59:05] [Server thread/WARN] [Translocator]: Mod Translocator is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 1.1.2.15
[12:59:05] [Server thread/WARN] [WR-CBE|Core]: Mod WR-CBE|Core is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 1.4.1.9
[12:59:05] [Server thread/WARN] [WR-CBE|Addons]: Mod WR-CBE|Addons is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 1.4.1.9
[12:59:05] [Server thread/WARN] [WR-CBE|Logic]: Mod WR-CBE|Logic is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 1.4.1.9
[12:59:05] [Server thread/WARN] [ForgeMicroblock]: Mod ForgeMicroblock is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 1.2.0.345
[12:59:05] [Server thread/WARN] [ForgeMultipart]: Mod ForgeMultipart is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 1.2.0.345
[12:59:05] [Server thread/WARN] [McMultipart]: Mod McMultipart is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 1.2.0.345
[12:59:05] [Server thread/WARN] [MrTJPCoreMod]: Mod MrTJPCoreMod is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 1.1.0.31
[12:59:05] [Server thread/INFO] [FML]: Forge Mod Loader has identified 162 mods to load
[12:59:05] [Server thread/INFO] [FML]: Found mod(s) [ExtraUtilities] containing declared API package baubles.api (owned by Baubles) without associated API reference
[12:59:05] [Server thread/INFO] [FML]: Found mod(s) [SGCraft] containing declared API package li.cil.oc.api.machine (owned by OpenComputers|Core) without associated API reference
[12:59:05] [Server thread/INFO] [FML]: Found mod(s) [SGCraft] containing declared API package li.cil.oc.api.network (owned by OpenComputers|Core) without associated API reference
[12:59:05] [Server thread/INFO] [FML]: Found mod(s) [SGCraft] containing declared API package li.cil.oc.api.fs (owned by OpenComputers|Core) without associated API reference
[12:59:05] [Server thread/INFO] [FML]: Found mod(s) [SGCraft] containing declared API package li.cil.oc.api (owned by OpenComputers|Core) without associated API reference
[12:59:05] [Server thread/INFO] [FML]: Found mod(s) [SGCraft] containing declared API package cofh.api.energy (owned by CoFHAPI) without associated API reference
[12:59:05] [Server thread/INFO] [FML]: Found mod(s) [SGCraft] containing declared API package li.cil.oc.api.driver (owned by OpenComputers|Core) without associated API reference
[12:59:05] [Server thread/INFO] [FML]: Found mod(s) [ImmersiveEngineering] containing declared API package cofh.api (owned by CoFHLib) without associated API reference
[12:59:05] [Server thread/INFO] [FML]: Found mod(s) [EnderIO] containing declared API package com.cricketcraft.chisel.api (owned by chisel) without associated API reference
[12:59:05] [Server thread/INFO] [FML]: Found mod(s) [RedstoneArsenal] containing declared API package ic2.api.tile (owned by IC2) without associated API reference
[12:59:08] [Server thread/ERROR] [FML]: The mod Translocator (Translocator) requires mods [NotEnoughItems] to be available
[12:59:08] [Server thread/ERROR]: Encountered an unexpected exception
cpw.mods.fml.common.MissingModsException:
Missing Mods:
NotEnoughItems : any
at cpw.mods.fml.common.Loader.sortModList(Loader.java:243) ~[Loader.class:?]
at cpw.mods.fml.common.Loader.loadMods(Loader.java:493) ~[Loader.class:?]
at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:87) ~[FMLServerHandler.class:?]
at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:314) ~[FMLCommonHandler.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117) ~[lt.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[12:59:08] [Server thread/ERROR]: This crash report has been saved to: /games/ni248314_1/ftproot/minecraftotherpacks/./crash-reports/crash-2016-02-21_12.59.08-server.txt
[12:59:08] [Server thread/WARN] [FML]: Can't revert to frozen GameData state without freezing first.
[12:59:08] [Server thread/INFO] [FML]: Applying holder lookups
[12:59:08] [Server thread/INFO] [FML]: Holder lookups applied
[12:59:08] [Server thread/INFO] [FML]: The state engine was in incorrect state CONSTRUCTING and forced into state SERVER_STOPPED. Errors may have been discarded.
Error   : Server failed to start 5 times. Not automatically restarting.
McMyAdmin Core Exception: An exception was thrown by the type initializer for System.Drawing.GDIPlus

**Comment by AtomSponge** [comment]
Inoffizielle Server werden nicht unterstützt, bitte nutze den offiziellen Download (siehe http://technicpack.net/modpack/hosencorp-2.732466, _Server Download_ auf der rechten Seite).
