### ISSUE TITLE
G-Portal Server Probleme

### ISSUE THREAD

**Issue by Clyde1512** [AtomSponge/hosencorp-2#20]
Hey, 
ich bräuchte mal eure Hilfe...
Ich habe mir einen Server bei G-Portal gemietet, und habe euer Modpack installiert (Das von Technick Laucncher.net)
und nun habe ich die Insatlationsbeschreibung verfolgt.
Hier einmal zum nachlesen:
https://www.g-portal.com/wiki/Wie_f%C3%BCge_ich_mein_eigenes_Modpack_ein%3F
Dar es bei euren Modpack keine FTBServer-Version.jar gibt , habe ich die Datei forge-1.7.10-10.13.4.1558-1.7.10-universal.jar umbenannt. 
Und nun bekomme ich beim Sarten diese Antwort:

A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException 
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
at java.lang.reflect.Method.invoke(Method.java:498) 
at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43) 
at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12) 
Caused by: java.lang.NoClassDefFoundError: org/apache/logging/log4j/Level 
at net.minecraft.launchwrapper.Launch.launch(Launch.java:94) 
at net.minecraft.launchwrapper.Launch.main(Launch.java:28) 
... 6 more 
Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.Level 
at java.net.URLClassLoader.findClass(URLClassLoader.java:381) 
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) 
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) 
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) 
... 8 more 
A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException 
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
at java.lang.reflect.Method.invoke(Method.java:498) 
at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43) 
at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12) 
Caused by: java.lang.NoClassDefFoundError: org/apache/logging/log4j/Level 
at net.minecraft.launchwrapper.Launch.launch(Launch.java:94) 
at net.minecraft.launchwrapper.Launch.main(Launch.java:28) 
... 6 more 
Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.Level 
at java.net.URLClassLoader.findClass(URLClassLoader.java:381) 
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) 
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) 
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) 
... 8 more 

Habe ich einfach nur die Falsche Datei umbenannt oder allgemein ganz falsch Installiert....
Brauche dringend Hilfe.
Danke schon mal im Voraus.

**Comment by AtomSponge** [comment]
Existiert der Ordner "libraries"?
Leider haben wir weder mit GPortal Erfahrungen, noch einen Server, womit wir dies testen könnten.

**Comment by Clyde1512** [comment]
ja das tut er, ich habe das Modpack so übernommen wie ich es gedownloaden habe, soll ich die ein Screen bei Twitter schicken, ich würde dir auch mein Passwort für g-portal sagen, damit du's ausprobieren kannst.

**Comment by AtomSponge** [comment]
Gib niemals Passwörter weiter, insbesondere dann nicht, wenn du die betroffene Person nicht kennst - also behalt das mal lieber für dich ;)
Bestenfalls wendest du dich in diesem Fall an den G-Portal Support, da wir hier leider nicht weiterhelfen können. Ich lasse das Issue trotzdem offen, falls noch Fragen aufkommen sollten.

**Comment by Clyde1512** [comment]
okay, war auch nur ein Angebot:D

**Comment by Clyde1512** [comment]
Ich habe jetzt bei G-Portal nachgefragt und die meinten da müsstet ihr mir helfen...
Hast du ne idee woran es liegen könnte??

**Comment by Bandelenth** [comment]
Wie von @AtomSponge schon weiter oben angemerkt kennen wir die genauen Umstände nicht, in einem "regulären" Setup funktioniert es wunderbar (ja, ich weiß, das ist keine Hilfe ;-)) Magst du mal probieren, ob der Server bei dir lokal so funktioniert (einfach per bat/sh/etc. je nach System starten)? Das würde zumindest Fehler auf unserer Seite ausschließen und auf ein Problem bei G-Portal hinweisen.

**Comment by Clyde1512** [comment]
Ich habe den server jetzt bei mir lokal gestartet, nach 3 minuten ladezeit hat er neue ordner erstellt, bzw. er hat den normalen ordner umgeschrieben. Wie gehe ich jetzt weiter vor??

**Comment by AtomSponge** [comment]
> neue ordner erstellt, bzw. er hat den normalen ordner umgeschrieben

Etwas genauere Fehlerbeschreibung bitte...?

**Comment by Clyde1512** [comment]
ich habe jetzt mehr Ordner, unzwar:
asm, blueprints, config, Flan, hats, imcScripts, Libraries, logs, mods, scripts, eula, forge-1.7...., mincraft_ser...., minetweaker, opencomputers...., opencomputers...., server.properties, start, start.sh

Und zumbeispiel die OpenComputers Sachen sind alle neu, soll ich das mal bei g-portal hochladen, oder wie erstelle ich draus jetzt den server????

**Comment by Bandelenth** [comment]
Das ist ein völlig reguläres Verhalten, der Server entpackt einfach benötigte Dateien... Genau genommen musst du damit gar nichts machen, da dasselbe Verhalten auch bei G-Portal auftreten würde, sofern der Server startet, das hat mit dem Problem selbst nichts zu tun.

**Comment by Clyde1512** [comment]
okay, also schetzen ich das das ein Fehler von G-Portal war, was muss ich jetzt noch machen um auf den Server zu joinen???( und um  festzulegen, wie viele mitspielen dürfen)

**Comment by AtomSponge** [comment]
> ich habe jetzt mehr Ordner, unzwar: [...]

Also liegt das Problem nicht bei uns, sondern bei G-Portal. Lad das Serverarchiv noch einmal komplett neu herunter und lad die entpackten Dateien bei G-Portal hoch - **alle** Dateien, auch die MinecraftServer-Jar. Darauf achten, dass die Forge-Jar gestartet wird, also diese zu server-file.jar umbenennen.

> okay, also schetzen ich das das ein Fehler von G-Portal war, was muss ich jetzt noch machen um auf den Server zu joinen???( und um festzulegen, wie viele mitspielen dürfen)

Dabei können wir dir leider nicht helfen, da wir das Webinterface von G-Portal nicht kennen. Normalerweise ändert man dies in der Datei _server.properties_, aber ich bezweifle, dass G-Portal dies zulässt, da man bei solchen Diensten normalerweise unter anderen nach Spieleranzahl zahlt.

Ich werde die Issue nun schließen, wenn du weitere Fragen hast, kannst du aber trotzdem noch hier fragen.
